# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubHookConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(default='', max_length=255)),
                ('path', models.CharField(blank=True, max_length=100)),
                ('post_install', models.CharField(blank=True, max_length=16)),
                ('type', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
