# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sloth_hook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubhookconf',
            options={'ordering': ('name', '-created')},
        ),
        migrations.RemoveField(
            model_name='githubhookconf',
            name='type',
        ),
        migrations.AddField(
            model_name='githubhookconf',
            name='name',
            field=models.CharField(default='sloth', max_length=32),
            preserve_default=False,
        ),
    ]
