# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sloth_hook', '0003_auto_20160621_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubhookconf',
            old_name='path',
            new_name='paths',
        ),
    ]
