# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sloth_hook', '0004_auto_20160622_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubhookconf',
            old_name='post_install',
            new_name='install',
        ),
    ]
